name: attendance_app
description: "A Flutter application for student attendance tracking."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  fluttertoast: ^8.2.12
  file_picker: ^10.0.0
  flutter_spinkit: ^5.1.0
  excel: ^4.0.6
  intl: ^0.20.2
  pdf: ^3.10.0
  printing: ^5.9.1
  shared_preferences: ^2.2.1
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/est.png